name: remote_state
version: 2.0.0
homepage: https://github.com/chimon2000/remote_state
description: Tools for mapping data from remote sources in Dart, similar to
  Elm's RemoteData.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  freezed_annotation: ^0.14.0
  meta: '>=1.0.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.11.5
  coverage: ^0.15.2
  freezed: ^0.14.0
  test: ^1.16.5
