name: remote_state
version: 1.5.0
homepage: https://github.com/chimon2000/remote_state
description: Tools for mapping data from remote sources in Dart, similar to
  Elm's RemoteData.
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  freezed_annotation: ^0.12.0
  meta: '>=1.0.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.10.9
  freezed: ^0.12.3
  test: ^1.15.7
  test_coverage: ^0.5.0
